language: node_js
node_js:
  - 6
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn add --force node-sass
  - yarn build
  - yarn coverage
after_script:
  - yarn codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master